// <auto-generated />
using System;
using FutureLife.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureLife.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutureLife.API.Models.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("RateToUsd")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode")
                        .IsUnique();

                    b.ToTable("ExchangeRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyCode = "USD",
                            RateToUsd = 1.0m,
                            UpdatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CurrencyCode = "EGP",
                            RateToUsd = 0.0204m,
                            UpdatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CurrencyCode = "SAR",
                            RateToUsd = 0.2667m,
                            UpdatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CurrencyCode = "AED",
                            RateToUsd = 0.2723m,
                            UpdatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CurrencyCode = "KWD",
                            RateToUsd = 3.2614m,
                            UpdatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CurrencyCode = "QAR",
                            RateToUsd = 0.2747m,
                            UpdatedAt = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FutureLife.API.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("AnnualSalaryGrowthRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("BMI")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CloseFriendsCount")
                        .HasColumnType("int");

                    b.Property<int>("CommunityEngagementScore")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentSavings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExerciseDaysPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InflationRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("InvestmentReturnRate")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PromotionProbability")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PromotionSalaryBoost")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("SleepHoursPerNight")
                        .HasColumnType("int");

                    b.Property<int>("SocialInteractionsPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("StressLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("FutureLife.API.Models.SimulationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BurnoutRisk")
                        .HasColumnType("float");

                    b.Property<double>("CareerGrowthIndex")
                        .HasColumnType("float");

                    b.Property<double>("CareerStagnationRisk")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EnergyDepletionRisk")
                        .HasColumnType("float");

                    b.Property<double>("EnergyScore10Y")
                        .HasColumnType("float");

                    b.Property<double>("EnergyScore1Y")
                        .HasColumnType("float");

                    b.Property<double>("EnergyScore5Y")
                        .HasColumnType("float");

                    b.Property<double>("FinancialCollapseRisk")
                        .HasColumnType("float");

                    b.Property<double>("HealthScore10Y")
                        .HasColumnType("float");

                    b.Property<double>("HealthScore1Y")
                        .HasColumnType("float");

                    b.Property<double>("HealthScore5Y")
                        .HasColumnType("float");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IsolationRisk")
                        .HasColumnType("float");

                    b.Property<double>("LifeStrategyScore")
                        .HasColumnType("float");

                    b.Property<double>("MonthlySavings")
                        .HasColumnType("float");

                    b.Property<string>("MonthlySnapshotsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("NetWorth10Y")
                        .HasColumnType("float");

                    b.Property<double>("OverallRiskIndex")
                        .HasColumnType("float");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.Property<double>("PromotionProbability")
                        .HasColumnType("float");

                    b.Property<double>("SalaryMultiplier")
                        .HasColumnType("float");

                    b.Property<double>("Savings10Y")
                        .HasColumnType("float");

                    b.Property<double>("Savings1Y")
                        .HasColumnType("float");

                    b.Property<double>("Savings5Y")
                        .HasColumnType("float");

                    b.Property<double>("SocialBalanceScore")
                        .HasColumnType("float");

                    b.Property<double>("StudyHours10Y")
                        .HasColumnType("float");

                    b.Property<double>("StudyHours1Y")
                        .HasColumnType("float");

                    b.Property<double>("StudyHours5Y")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("YearlySnapshotsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("SimulationResults");
                });

            modelBuilder.Entity("FutureLife.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FutureLife.API.Models.Profile", b =>
                {
                    b.HasOne("FutureLife.API.Models.User", "User")
                        .WithMany("Profiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FutureLife.API.Models.SimulationResult", b =>
                {
                    b.HasOne("FutureLife.API.Models.Profile", null)
                        .WithMany("SimulationResults")
                        .HasForeignKey("ProfileId");

                    b.HasOne("FutureLife.API.Models.User", "User")
                        .WithMany("SimulationResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FutureLife.API.Models.Profile", b =>
                {
                    b.Navigation("SimulationResults");
                });

            modelBuilder.Entity("FutureLife.API.Models.User", b =>
                {
                    b.Navigation("Profiles");

                    b.Navigation("SimulationResults");
                });
#pragma warning restore 612, 618
        }
    }
}
